CREATE DATABASE IF NOT EXISTS pos_auth;
CREATE DATABASE IF NOT EXISTS pos_store;
CREATE DATABASE IF NOT EXISTS pos_catalog;
CREATE DATABASE IF NOT EXISTS pos_sales;
CREATE DATABASE IF NOT EXISTS pos_billing;
CREATE DATABASE IF NOT EXISTS pos_report;
